USE LIBRARY

CREATE TABLE IF NOT EXISTS `PERSON` (
`ID` BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
`FIRST_NAME` VARCHAR(20) NOT NULL,
`LAST_NAME` VARCHAR(20) NOT NULL,
`ADDRESS` VARCHAR(80) NOT NULL,
`GENDER` VARCHAR(6) NOT NULL